#!/usr/bin/env bash
# worktree-port-alloc.sh — Assign unique port ranges per git worktree
#
# Prevents port collisions when running multiple dev servers across worktrees.
# Detects base ports from .env / docker-compose.yml, applies offset per worktree index,
# and writes .env.worktree for the current worktree.
#
# Usage:
#   worktree-port-alloc.sh [worktree_path]
#   # defaults to current directory
#
# Output: .env.worktree in the worktree root with PORT_OFFSET and adjusted port vars.
# Source it in your dev scripts: source .env.worktree
#
# Ref: Neil Kakkar "How I'm Productive with Claude Code" — worktree port allocation

set -euo pipefail

WORKTREE_PATH="${1:-$(pwd)}"
PORT_STEP=100  # offset increment per worktree

# --- Determine worktree index ---
get_worktree_index() {
    local target
    target="$(cd "$WORKTREE_PATH" && git rev-parse --show-toplevel 2>/dev/null || echo "$WORKTREE_PATH")"

    local index=0
    while IFS= read -r line; do
        # git worktree list outputs: /path/to/worktree  <hash> [branch]
        local wt_path
        wt_path="$(echo "$line" | awk '{print $1}')"
        if [[ "$wt_path" == "$target" ]]; then
            echo "$index"
            return
        fi
        ((index++))
    done < <(git -C "$WORKTREE_PATH" worktree list 2>/dev/null)

    # Fallback: hash-based index if not found in worktree list
    echo $(( $(echo "$target" | cksum | awk '{print $1}') % 50 + 1 ))
}

# --- Detect base ports from .env ---
detect_env_ports() {
    local env_file="$1"
    [[ -f "$env_file" ]] || return

    # Extract lines matching PORT= patterns (e.g., PORT=3000, API_PORT=8080)
    grep -E '^[A-Z_]*PORT\s*=' "$env_file" 2>/dev/null || true
}

# --- Detect base ports from docker-compose.yml ---
detect_compose_ports() {
    local compose_file="$1"
    [[ -f "$compose_file" ]] || return

    # Extract host ports from "HOST:CONTAINER" mappings
    grep -E '^\s*-\s*"?[0-9]+:[0-9]+"?' "$compose_file" 2>/dev/null | \
        sed -E 's/.*"?([0-9]+):[0-9]+"?.*/\1/' || true
}

# --- Find the main worktree root (for reading base .env) ---
get_main_worktree() {
    git -C "$WORKTREE_PATH" worktree list 2>/dev/null | head -1 | awk '{print $1}'
}

# --- Main ---
main() {
    local index
    index="$(get_worktree_index)"

    # Main worktree (index 0) needs no offset
    if [[ "$index" -eq 0 ]]; then
        echo "[worktree-port-alloc] Main worktree — no offset needed" >&2
        return 0
    fi

    local offset=$(( index * PORT_STEP ))
    local main_wt
    main_wt="$(get_main_worktree)"
    local output_file="$WORKTREE_PATH/.env.worktree"

    {
        echo "# Auto-generated by worktree-port-alloc.sh"
        echo "# Worktree index: $index, offset: +$offset"
        echo "PORT_OFFSET=$offset"
        echo ""
    } > "$output_file"

    # Process .env from main worktree
    local base_env="$main_wt/.env"
    if [[ -f "$base_env" ]]; then
        while IFS='=' read -r key value; do
            # Skip comments and empty lines
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            # Strip inline comments and whitespace
            value="$(echo "$value" | sed 's/#.*//' | xargs)"
            # Check if value is a port number
            if [[ "$value" =~ ^[0-9]+$ ]] && [[ "$value" -ge 1024 ]] && [[ "$value" -le 65435 ]]; then
                local new_port=$(( value + offset ))
                echo "${key}=${new_port}"
            fi
        done < <(detect_env_ports "$base_env") >> "$output_file"
    fi

    # Process docker-compose.yml ports
    local compose_file="$main_wt/docker-compose.yml"
    if [[ -f "$compose_file" ]]; then
        echo "" >> "$output_file"
        echo "# docker-compose port offsets (apply manually or via override)" >> "$output_file"
        while IFS= read -r port; do
            port="$(echo "$port" | xargs)"
            [[ -z "$port" ]] && continue
            echo "# ${port} -> $(( port + offset ))" >> "$output_file"
        done < <(detect_compose_ports "$compose_file")
    fi

    echo "[worktree-port-alloc] Generated $output_file (index=$index, offset=+$offset)" >&2

    # Add .env.worktree to .gitignore if not already
    local gitignore="$WORKTREE_PATH/.gitignore"
    if [[ -f "$gitignore" ]]; then
        if ! grep -qF '.env.worktree' "$gitignore" 2>/dev/null; then
            echo '.env.worktree' >> "$gitignore"
        fi
    fi
}

main
