#!/usr/bin/env python3
"""Project-specific Context MCP Server — keyword search over project knowledge.

Based on Codified Context paper (Vasilopoulos, 2026):
5-tool knowledge retrieval service for project-specific knowledge base.

Usage:
  python3 server.py list                  # List all subsystems
  python3 server.py get <key>             # Get subsystem details
  python3 server.py find <task desc>      # Find relevant context
  python3 server.py search <query>        # Full-text search
  python3 server.py suggest <task desc>   # Suggest best agent

Template generated by /init-project skill. Customize KNOWLEDGE_DIRS for your project.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

# --- Configuration (customize per project) ---

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
KNOWLEDGE_DIRS = [
    PROJECT_ROOT / "docs",
    PROJECT_ROOT / ".claude" / "references",
    PROJECT_ROOT / "references",
]
AGENT_DIR = PROJECT_ROOT / ".claude" / "agents"


def _index_documents() -> dict[str, dict[str, Any]]:
    """Build an in-memory index of all knowledge documents."""
    index: dict[str, dict[str, Any]] = {}
    for doc_dir in KNOWLEDGE_DIRS:
        if not doc_dir.is_dir():
            continue
        for md_file in doc_dir.rglob("*.md"):
            key = md_file.stem
            try:
                content = md_file.read_text(encoding="utf-8")
            except OSError as exc:
                sys.stderr.write(f"[context-mcp] read error {md_file}: {exc}\n")
                continue
            title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
            title = title_match.group(1) if title_match else key
            headings = re.findall(r"^#{1,3}\s+(.+)$", content, re.MULTILINE)
            keywords = " ".join(headings).lower()
            index[key] = {
                "title": title,
                "path": str(md_file.relative_to(PROJECT_ROOT)),
                "keywords": keywords,
                "lines": len(content.splitlines()),
                "content_preview": content[:500],
            }
    return index


def _index_agents() -> dict[str, dict[str, Any]]:
    """Build an index of available agents."""
    agents: dict[str, dict[str, Any]] = {}
    if not AGENT_DIR.is_dir():
        return agents
    for agent_file in AGENT_DIR.glob("*.md"):
        try:
            content = agent_file.read_text(encoding="utf-8")
        except OSError as exc:
            sys.stderr.write(f"[context-mcp] read error {agent_file}: {exc}\n")
            continue
        name = agent_file.stem
        desc_match = re.search(r"^description:\s*(.+)$", content, re.MULTILINE)
        description = desc_match.group(1).strip() if desc_match else ""
        agents[name] = {
            "name": name,
            "description": description,
            "path": str(agent_file.relative_to(PROJECT_ROOT)),
        }
    return agents


# --- MCP Tool Implementations ---


def list_subsystems() -> list[dict[str, Any]]:
    """List all documented subsystems in the knowledge base."""
    index = _index_documents()
    return [
        {"key": k, "title": v["title"], "path": v["path"], "lines": v["lines"]}
        for k, v in sorted(index.items())
    ]


def get_files_for_subsystem(key: str) -> dict[str, Any] | None:
    """Get detailed information about a specific subsystem."""
    index = _index_documents()
    return index.get(key)


def find_relevant_context(task: str) -> list[dict[str, Any]]:
    """Find documents relevant to a given task description (keyword match)."""
    index = _index_documents()
    task_lower = task.lower()
    task_words = set(re.findall(r"\w+", task_lower))

    scored: list[tuple[float, str, dict[str, Any]]] = []
    for key, doc in index.items():
        score = sum(1 for w in task_words if w in doc["keywords"])
        if score > 0:
            scored.append((score, key, doc))

    scored.sort(key=lambda x: -x[0])
    return [
        {"key": k, "title": d["title"], "path": d["path"], "relevance": s}
        for s, k, d in scored[:5]
    ]


def search_context_documents(query: str) -> list[dict[str, Any]]:
    """Full-text search across all knowledge documents."""
    index = _index_documents()
    query_lower = query.lower()
    results = []
    for key, doc in index.items():
        if (
            query_lower in doc["keywords"]
            or query_lower in doc["content_preview"].lower()
        ):
            results.append({"key": key, "title": doc["title"], "path": doc["path"]})
    return results[:10]


def suggest_agent(task: str) -> list[dict[str, Any]]:
    """Suggest the best agent(s) for a given task."""
    agents = _index_agents()
    task_lower = task.lower()
    task_words = set(re.findall(r"\w+", task_lower))

    scored: list[tuple[float, str, dict[str, Any]]] = []
    for _name, agent in agents.items():
        desc_words = set(re.findall(r"\w+", agent["description"].lower()))
        score = len(task_words & desc_words)
        if score > 0:
            scored.append((score, _name, agent))

    scored.sort(key=lambda x: -x[0])
    return [
        {"name": a["name"], "description": a["description"], "relevance": s}
        for s, _, a in scored[:3]
    ]


# --- CLI interface ---

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: server.py <command> [args]")
        print("Commands: list, get <key>, find <task>, search <query>, suggest <task>")
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == "list":
        print(json.dumps(list_subsystems(), indent=2, ensure_ascii=False))
    elif cmd == "get" and len(sys.argv) > 2:
        result = get_files_for_subsystem(sys.argv[2])
        print(json.dumps(result, indent=2, ensure_ascii=False))
    elif cmd == "find" and len(sys.argv) > 2:
        print(
            json.dumps(
                find_relevant_context(" ".join(sys.argv[2:])),
                indent=2,
                ensure_ascii=False,
            )
        )
    elif cmd == "search" and len(sys.argv) > 2:
        print(
            json.dumps(
                search_context_documents(" ".join(sys.argv[2:])),
                indent=2,
                ensure_ascii=False,
            )
        )
    elif cmd == "suggest" and len(sys.argv) > 2:
        print(
            json.dumps(
                suggest_agent(" ".join(sys.argv[2:])), indent=2, ensure_ascii=False
            )
        )
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)
